### ISSUE TITLE
How to visualise the deployment and infrastructure metrics in Datadog UI?

### ISSUE THREAD

**Issue by pawandhiman10** [DataDog/kong-plugin-ddtrace#14]
Kong version: 3.3.0
With this plugin, we are able to send the traces successfully on port 8126.
But not able to figure out anything related to the metrics under the Infrastructure and Deployment Tabs of the Services page in Datadog UI.
We have already set the DD_ENV, DD_SERVICE, and DD_VERSION environment variables but not working as expected, we believe this is due to the fact that we are not connecting with 8125 port to have the metrics in DD.
Could you please help here or suggest how we can get the version and infrastructure metrics?

**Comment by dmehala** [comment]
Hello @pawandhiman10,

Appreciation for highlighting this issue. I'm pleased to share that the fix has been merged and will be incorporated into the upcoming release. Once the release is complete, I'll provide instructions on setting up DD_ENV, DD_SERVICE, and DD_VERSION.

**Comment by dmehala** [comment]
I released `v0.2.0`. Thanks for your patience!
